ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "My first commit"
On branch main

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        add_num.py

nothing added to commit but untracked files present (use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "My first commit"
[main (root-commit) 2216438] My first commit
 1 file changed, 10 insertions(+)
 create mode 100644 add_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git status
On branch main
nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "My first commit"
On branch main
nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/python/first.git

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Not Found
fatal: repository 'https://github.com/imuttam/python/first.git/' not found

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ https://github.com/imuttam/Python.git
bash: https://github.com/imuttam/Python.git: No such file or directory

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/Python.git
error: remote origin already exists.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git init
Reinitialized existing Git repository in C:/Users/ARTTC/Documents/python/.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'new commit'
On branch main
nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/Python.git
error: remote origin already exists.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Not Found
fatal: repository 'https://github.com/imuttam/python/first.git/' not found

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote -v
origin  https://github.com/imuttam/python/first.git (fetch)
origin  https://github.com/imuttam/python/first.git (push)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/python/first.git
error: remote origin already exists.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote rm origin

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/Python.git

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
error: unable to read askpass response from 'C:/Program Files/Git/mingw32/bin/git-askpass.exe'
Password for 'https://Kanchan11@@github.com':

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/imuttam/Python.git/'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Permission to imuttam/Python.git denied to imuttam.
fatal: unable to access 'https://github.com/imuttam/Python.git/': The requested URL returned error: 403

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main


ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git clone https://github.com/imuttam/REPO.git
Cloning into 'REPO'...
remote: Repository not found.
fatal: repository 'https://github.com/imuttam/REPO.git/' not found

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git clone https://github.com/imuttam/Python.git
Cloning into 'Python'...
warning: You appear to have cloned an empty repository.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Permission to imuttam/Python.git denied to imuttam.
fatal: unable to access 'https://github.com/imuttam/Python.git/': The requested URL returned error: 403

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git config --list
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\ARTTC\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/ARTTC/Documents/Git
user.name=iamuttam
user.email=uttam.uk@gmail.com
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
:
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\ARTTC\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/ARTTC/Documents/Git
user.name=iamuttam
user.email=uttam.uk@gmail.com
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
:
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\ARTTC\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/ARTTC/Documents/Git
user.name=iamuttam
user.email=uttam.uk@gmail.com
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
:
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\ARTTC\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/ARTTC/Documents/Git
user.name=iamuttam
user.email=uttam.uk@gmail.com
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/imuttam/Python.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git clone https://github.com/imuttam/Python.git
fatal: destination path 'Python' already exists and is not an empty directory.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Permission to imuttam/Python.git denied to imuttam.
fatal: unable to access 'https://github.com/imuttam/Python.git/': The requested URL returned error: 403

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git config --list
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\ARTTC\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/ARTTC/Documents/Git
user.name=iamuttam
user.email=uttam.uk@gmail.com
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/imuttam/Python.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git init
Reinitialized existing Git repository in C:/Users/ARTTC/Documents/python/.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "first commit"
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Python/
        average_of_num.py

nothing added to commit but untracked files present (use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A
error: 'Python/' does not have a commit checked out
fatal: adding files failed

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ls
Python/  add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add add_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "2nd commit"
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Python/
        average_of_num.py

nothing added to commit but untracked files present (use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A
error: 'Python/' does not have a commit checked out
fatal: adding files failed

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ls
Python/  add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ cd Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A
.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git add -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git commit -m "2nd commit"
On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git clone https://github.com/imuttam/Python.git
Cloning into 'Python'...
warning: You appear to have cloned an empty repository.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/imuttam/Python.git'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/imuttam/Python.git'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git add -A
error: 'Python/' does not have a commit checked out
fatal: adding files failed

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git push -u origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/imuttam/Python.git'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git list
git: 'list' is not a git command. See 'git --help'.

The most similar commands are
        bisect
        rev-list

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git --list
unknown option: --list
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A
.git/  Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git reset --hard~
error: unknown option `hard~'
usage: git reset [--mixed | --soft | --hard | --merge | --keep] [-q] [<commit>]
   or: git reset [-q] [<tree-ish>] [--] <pathspec>...
   or: git reset [-q] [--pathspec-from-file [--pathspec-file-nul]] [<tree-ish>]
   or: git reset --patch [<tree-ish>] [--] [<pathspec>...]
   or: DEPRECATED: git reset [-q] [--stdin [-z]] [<tree-ish>]

    -q, --quiet           be quiet, only report errors
    --no-refresh          skip refreshing the index after reset
    --mixed               reset HEAD and index
    --soft                reset only HEAD
    --hard                reset HEAD, index and working tree
    --merge               reset HEAD, index and working tree
    --keep                reset HEAD but keep local changes
    --recurse-submodules[=<reset>]
                          control recursive updating of submodules
    -p, --patch           select hunks interactively
    -N, --intent-to-add   record only the fact that removed paths will be added later
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character
    -z                    DEPRECATED (use --pathspec-file-nul instead): paths are separated with NUL character
    --stdin               DEPRECATED (use --pathspec-from-file=- instead): read paths from <stdin>


ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ git reset --hard

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A
.git/  Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ cd Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python/Python (main)
$ ls

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python/Python (main)
$ ls -A
.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python/Python (main)
$ cd ..

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A
.git/  Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ rm Python/
rm: cannot remove 'Python/': Is a directory

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ rm -r Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A
.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ rm -r .git/
rm: remove write-protected regular file '.git/objects/4b/825dc642cb6eb9a060e54bf8d69288fbee4904'?
rm: cannot remove '.git/objects/4b': Directory not empty

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ rm  .git/
rm: cannot remove '.git/': Is a directory

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ rm  -r .git/
rm: remove write-protected regular file '.git/objects/4b/825dc642cb6eb9a060e54bf8d69288fbee4904'? yes

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ ls -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python/Python (main)
$ cd ..

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ls -A
.git/  Python/  add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ rm -r Python/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ls -A
.git/  add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        average_of_num.py

nothing added to commit but untracked files present (use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git reset --hard
HEAD is now at 2216438 My first commit

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git clean
fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git --clean
unknown option: --clean
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git reset --help



ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git reset --help?
error: unknown option `help?'
usage: git reset [--mixed | --soft | --hard | --merge | --keep] [-q] [<commit>]
   or: git reset [-q] [<tree-ish>] [--] <pathspec>...
   or: git reset [-q] [--pathspec-from-file [--pathspec-file-nul]] [<tree-ish>]
   or: git reset --patch [<tree-ish>] [--] [<pathspec>...]
   or: DEPRECATED: git reset [-q] [--stdin [-z]] [<tree-ish>]

    -q, --quiet           be quiet, only report errors
    --no-refresh          skip refreshing the index after reset
    --mixed               reset HEAD and index
    --soft                reset only HEAD
    --hard                reset HEAD, index and working tree
    --merge               reset HEAD, index and working tree
    --keep                reset HEAD but keep local changes
    --recurse-submodules[=<reset>]
                          control recursive updating of submodules
    -p, --patch           select hunks interactively
    -N, --intent-to-add   record only the fact that removed paths will be added later
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character
    -z                    DEPRECATED (use --pathspec-file-nul instead): paths are separated with NUL character
    --stdin               DEPRECATED (use --pathspec-from-file=- instead): read paths from <stdin>


ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ls -A
.git/  add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ rm -r .git/
rm: remove write-protected regular file '.git/objects/22/164380f83174375e15f19954f76fe95aa09e28'? yes
rm: remove write-protected regular file '.git/objects/39/8c88ed004b8bc165188b8b18a5a8ca0fd0ddac'? yes
rm: remove write-protected regular file '.git/objects/4b/825dc642cb6eb9a060e54bf8d69288fbee4904'? y
rm: remove write-protected regular file '.git/objects/63/204bbddc7dc2a7e0ac0dce47ae66d59bf3a54b'? yes

ARTTC@ARTTC-HP MINGW32 ~/Documents/python
$ ls -A
add_num.py  average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python
$ python add_num.py
Enter how many number you want to add: 2
 Enter number: 2
 Enter number: 3
Sum of all numbers are: 5

ARTTC@ARTTC-HP MINGW32 ~/Documents/python
$ git status
fatal: not a git repository (or any of the parent directories): .git

ARTTC@ARTTC-HP MINGW32 ~/Documents/python
$ git init
Initialized empty Git repository in C:/Users/ARTTC/Documents/python/.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git status
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        add_num.py
        average_of_num.py

nothing added to commit but untracked files present (use "git add" to track)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "initial commit"
[main (root-commit) 5e36e4a] initial commit
 2 files changed, 13 insertions(+)
 create mode 100644 add_num.py
 create mode 100644 average_of_num.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote add origin https://github.com/imuttam/Python.git

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Permission to imuttam/Python.git denied to imuttam.
fatal: unable to access 'https://github.com/imuttam/Python.git/': The requested URL returned error: 403

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/imuttam/Python.git/'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote set-url origin https://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@github.com/imuttam/Python

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/imuttam/Python/'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote set-url origin https://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@github.com/imuttam/Python

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 464 bytes | 464.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/imuttam/Python
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add -A

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m "new commit"
[main 551dfc9] new commit
 1 file changed, 6 insertions(+), 1 deletion(-)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
To https://github.com/imuttam/Python
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/imuttam/Python'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git branch -M main

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
To https://github.com/imuttam/Python
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/imuttam/Python'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
To https://github.com/imuttam/Python
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/imuttam/Python'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote set-url origin https://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@github.com/imuttam/Python

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
To https://github.com/imuttam/Python
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/imuttam/Python'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ ^C

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git pull origin master
fatal: couldn't find remote ref master

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git pull --rebase origin master
fatal: couldn't find remote ref master

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git init
Reinitialized existing Git repository in C:/Users/ARTTC/Documents/python/.git/

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'new commit'
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git remote set-url origin https://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@github.com/imuttam/Python

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git pull --rebase origin master
fatal: couldn't find remote ref master

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -f origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/imuttam/Python'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -f origin main
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 828 bytes | 828.00 KiB/s, done.
Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/imuttam/Python
 + 689b7e5...551dfc9 main -> main (forced update)

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m ' added third'
[main dafcc5b]  added third
 1 file changed, 9 insertions(+)
 create mode 100644 larger_of_two.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 424 bytes | 424.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/imuttam/Python
   551dfc9..dafcc5b  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added natural_sum'
[main aec7e3a] added natural_sum
 2 files changed, 16 insertions(+)
 create mode 100644 even_odd.py
 create mode 100644 natural_num_sum.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 693 bytes | 693.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/imuttam/Python
   dafcc5b..aec7e3a  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added turtle_animatedCircle'
[main b194242] added turtle_animatedCircle
 1 file changed, 7 insertions(+)
 create mode 100644 turtle_animatedCircle.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 394 bytes | 394.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/imuttam/Python
   aec7e3a..b194242  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added level-1'
[main 88964c2] added level-1
 6 files changed, 43 insertions(+)
 rename add_num.py => Level-1/add_num.py (100%)
 rename average_of_num.py => Level-1/average_of_num.py (100%)
 create mode 100644 Level-1/digit_at_ones_place.py
 create mode 100644 area_circle.py
 create mode 100644 area_traingle.py
 create mode 100644 pass_fail.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.27 KiB | 1.27 MiB/s, done.
Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/imuttam/Python
   b194242..88964c2  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added more'
[main 9214100] added more
 5 files changed, 27 insertions(+)
 rename even_odd.py => Level-1/even_odd.py (100%)
 rename larger_of_two.py => Level-1/larger_of_two.py (100%)
 rename pass_fail.py => Level-1/pass_fail.py (100%)
 create mode 100644 Level-1/swap_num.py
 create mode 100644 farenheit_celsius_conversion.py

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1010 bytes | 1010.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/imuttam/Python
   88964c2..9214100  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added 19-10-23'

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ [main d63703e] added 19-10-23
 16 files changed, 54 insertions(+)
 rename {Level-1 => beginner}/add_num.py (100%)
 rename area_circle.py => beginner/area_circle.py (100%)
 rename area_traingle.py => beginner/area_traingle.py (100%)
 rename {Level-1 => beginner}/average_of_num.py (100%)
 create mode 100644 beginner/compund_interest.py
 rename {Level-1 => beginner}/digit_at_ones_place.py (100%)
 rename {Level-1 => beginner}/even_odd.py (100%)
 rename farenheit_celsius_conversion.py => beginner/farenheit_celsius_conversion.py (100%)
 rename {Level-1 => beginner}/larger_of_two.py (100%)
 rename natural_num_sum.py => beginner/natural_num_sum.py (100%)
 rename {Level-1 => beginner}/pass_fail.py (100%)
 create mode 100644 beginner/simple_interest.py
 rename {Level-1 => beginner}/swap_num.py (100%)
 rename turtle_animatedCircle.py => beginner/turtle_animatedCircle.py (100%)
 create mode 100644 ifElse/vote_eligibility.py
 create mode 100644 input_character_type.py


ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git add .

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'commited at 19-10-23'
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git commit -m 'added 19-10-23'
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$ git push -u origin main
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 4 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (15/15), 2.56 KiB | 875.00 KiB/s, done.
Total 15 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/imuttam/Python
   9214100..d63703e  main -> main
branch 'main' set up to track 'origin/main'.

ARTTC@ARTTC-HP MINGW32 ~/Documents/python (main)
$
